name: reciclando
description: "App de reciclaje colaborativa - Reciclando"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Env, Security & Connectivity
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^6.1.1

  # Google Maps & Location
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2

  # Media
  image_picker: ^1.2.1

  # Persistencia local
  shared_preferences: ^2.5.4

  # Utilities
  intl: ^0.20.2
  logger: ^2.6.0
  
  # Notificaciones y comunicación con backend
  http: ^1.2.1
  flutter_local_notifications: ^21.0.0
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  # Configuración de entornos
  assets:
    - .env
    - .env.dev